version: '3'
services:

  mysql:
    container_name: mysql_container
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mount/dev/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    command: mysqld --sql_mode=""

  spring-app:
    image: ilyeshamdi/spring-app:latest
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/devops
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "8089:8089"
